disable stetho due to crashes:
07-27 21:40:28.635 15072-15072/org.tribler.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tribler.android, PID: 15072
                                                                     Theme: themes:{}
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                         at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
                                                                         at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
                                                                         at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
                                                                         at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
                                                                         at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
                                                                         at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
                                                                         at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)